name: CI

on:
  push:
    branches: [ master, release/* ]
  pull_request:
    branches: [ master ]

jobs:
  build_apk:
    name: Build an APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        
      - name: install deps
        uses: steebchen/flutter@v1.1.0
        with:
          args: pub get
      
#       - name: run tests
#         uses: steebchen/flutter@v1.1.0
#         with:
#           args: test
      
      - name: build apk
        uses: steebchen/flutter@v1.1.0
        with:
          args: build apk --release --split-per-abi
